### ISSUE TITLE
Transcribe Vendrame Interview

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/lab-wiki#3]
Please, add Wagner's interview notes to the google doc (https://docs.google.com/document/d/1nD1z1W_0g_3H74goFD-_MvTrjm5esU3KgLni8qYAX8M/edit?ts=5a4e5513) or summarize as a comment here. I'd like to highlight him for 'what is NOT agroecology'.

**Comment by mesawendy0** [comment]
I have added the notes to our interview. I did not get the opportunity to write his summary, I will do this first thing tomorrow.

**Comment by brymz** [comment]
Thanks. Sounds good. Then you can close your first issue!

**Comment by mesawendy0** [comment]
After taking some notes, I don't believe Wagner can't be placed under the What is not Agroecology. He mostly talked about the BioFuel project (which can be a bit of a soft spot depened on the audience reading). The way that  I can spin this is by highlighting and alternate form of sustainability, and not being agroecology because it is has no direct impact on the environment. But has future implications once it leaves the lab?

**Comment by brymz** [comment]
A double negative(?), so you think Wagner’s work does fit into the the ‘what is not agriecoligy’ story. I have planned to talk about his bioreactor tissue culture, so no spin necessary. My start of the post is in the shared drive. His section will focus on how propagation practices are not agroecology in and of themselves, but can be with context.

**Comment by mesawendy0** [comment]
I understand your poi. I had a follow-up meeting with him yesterday and wrote my notes on commercial vs conservation. Please let me know if you need any more notes.
