### ISSUE TITLE
What is agroecology post draft finalization and publishing

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/lab-wiki#4]
- [x] We are waiting on a determination for where this will be published (TREC, IFAS, Agroecology).
- [x] Reformat away from highlight boxes

**Comment by brymz** [comment]
I revised the post away from highlight boxes. Alec is looking into a plug-in that would allow us a little more flexibility with page formatting.

Alec authorized a UF Agroecology blog, which I will need to discuss at our team meeting next Wed. We will decide how to proceed with publishing the post then.
 
Next steps, please:
- [x] have a final review of the post for grammar and content.
- [x] check to make sure all of the links work.

**Comment by mesawendy0** [comment]
Completed.

In my honest opinion (not trying to underestimate the knowledge of our extension agents, and other target audience) but this is a front heavy blog. I'm assuming that what you are aiming for, reads more like a scientific paper rather than a casual blog read introducing a new topic to someone. We can go over it at lab meeting, or leave it as it.

**Comment by brymz** [comment]
Thanks. I suppose your assessment is reasonable. The blog is a two-page summary of my scientific paper (Brym and Reeve 2016). What would you do differently to make it more reader friendly? To be clear, my goal is not to make it a casual blog, but rather to have an approachable and engaging blog that clearly delivers scientific content for a broad (educated adult?) audience.
